package VIEW;

import DAO.ReservaDAO;
import DTO.ReservaDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author Salatiel
 */
public class FrmConfirmaCheckout extends javax.swing.JInternalFrame {

    private FrmCheckout parentFrame;

    /**
     * Creates new form FrmConfirmaCheckout
     */
    public FrmConfirmaCheckout(FrmCheckout parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCancelar = new javax.swing.JButton();
        BtnSalvarCheckin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtIDCliente = new javax.swing.JTextField();
        txtIDQuarto = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdReserva = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCheckout = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnSalvarCheckin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalvarCheckin.setText("Salvar Check-out");
        BtnSalvarCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarCheckinActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nº Quarto");

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeCliente.setFocusable(false);

        txtIDCliente.setEditable(false);
        txtIDCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtIDCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtIDCliente.setToolTipText("");
        txtIDCliente.setFocusable(false);
        txtIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDClienteActionPerformed(evt);
            }
        });

        txtIDQuarto.setEditable(false);
        txtIDQuarto.setBackground(new java.awt.Color(255, 255, 255));
        txtIDQuarto.setForeground(new java.awt.Color(0, 0, 0));
        txtIDQuarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtIDQuarto.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");

        txtIdReserva.setEditable(false);
        txtIdReserva.setBackground(new java.awt.Color(255, 255, 255));
        txtIdReserva.setForeground(new java.awt.Color(0, 0, 0));
        txtIdReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtIdReserva.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nº Reserva");

        txtCheckout.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckout.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCheckout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Check-out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSalvarCheckin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCheckout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(txtNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvarCheckin)
                    .addComponent(BtnCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarCheckinActionPerformed
        if (AlterarCheckout()) {
            // Notifique a janela principal e feche esta janela
            parentFrame.onCheckinDataConfirmed();
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar a data de check-in", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSalvarCheckinActionPerformed

    private void txtIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDClienteActionPerformed

    }//GEN-LAST:event_txtIDClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnSalvarCheckin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField txtCheckout;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JFormattedTextField txtIDQuarto;
    private javax.swing.JFormattedTextField txtIdReserva;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables

    private boolean AlterarCheckout() {
        String id_reserva, data_checkout, status;

        data_checkout = txtCheckout.getText();
        id_reserva = txtIdReserva.getText();

        String formataDatacheckout = convertDateFormat(data_checkout);

        if (formataDatacheckout == null) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido. Por favor, use o formato dd/MM/yyyy.");
            return false;
        }

        ReservaDTO objCadReservaDTO = new ReservaDTO();
        status = "Finalizado";
        objCadReservaDTO.setDataCheckout(formataDatacheckout);
        objCadReservaDTO.setId(id_reserva);
        objCadReservaDTO.setStatus(status);

        ReservaDAO objCadReservaDAO = new ReservaDAO();

        try {
            objCadReservaDAO.AlterarDataCheckout(objCadReservaDTO);
            JOptionPane.showMessageDialog(null, "Data de check-out Registrada");
            return true; // Retorna true se a operação for bem-sucedida
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao registrar a data de check-out: " + e.getMessage());
            return false; // Retorna false se houver um erro ao alterar a data de check-in
        }

    }

    private String convertDateFormat(String dateStr) {
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = inputFormat.parse(dateStr);
            return outputFormat.format(date);
        } catch (ParseException e) {
            return null;
        }
    }

    public void preencherReserva(String idReserva, String idCliente, String nome, String idQuarto) {
        txtIdReserva.setText(idReserva);
        txtIDQuarto.setText(idQuarto);
        txtIDCliente.setText(idCliente);
        txtNomeCliente.setText(nome);
    }
}
