package VIEW;

import DAO.ReservaDAO;
import DTO.ReservaDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author Salatiel
 */
public class FrmConsultaCheckout extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultaCheckout
     */
    public FrmConsultaCheckout() {
        initComponents();
        listarReservas();
        BtnEditarReserva.setEnabled(false);
        BtnExcluirrreserva.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDreserva = new javax.swing.JTextField();
        BtnEditarReserva = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCheckout = new javax.swing.JTable();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnExcluirrreserva = new javax.swing.JButton();
        txtIDQuarto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnCarregarCampos = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        txtIDreserva1 = new javax.swing.JTextField();
        BtnEditarReserva1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCheckout1 = new javax.swing.JTable();
        txtNomeCliente1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnExcluirrreserva1 = new javax.swing.JButton();
        txtIDQuarto1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIDCliente1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDataCheckout1 = new javax.swing.JTextField();
        BtnCarregarCampos1 = new javax.swing.JButton();
        txtDataCheckout = new javax.swing.JFormattedTextField();

        setClosable(true);

        txtIDreserva.setEditable(false);
        txtIDreserva.setBackground(new java.awt.Color(255, 255, 255));
        txtIDreserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDreserva.setForeground(new java.awt.Color(51, 51, 51));
        txtIDreserva.setFocusable(false);

        BtnEditarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEditarReserva.setText("Editar reserva");
        BtnEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarReservaActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        jDesktopPane1.setEnabled(false);
        jDesktopPane1.setFocusable(false);

        tabelaCheckout.setBackground(new java.awt.Color(255, 255, 255));
        tabelaCheckout.setForeground(new java.awt.Color(0, 0, 0));
        tabelaCheckout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Reserva", "ID Cliente", "Nome", "ID Quarto", "Data Check-in",  "Data Check-in","Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaCheckout);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeCliente.setForeground(new java.awt.Color(51, 51, 51));
        txtNomeCliente.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nº Quarto");

        BtnExcluirrreserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnExcluirrreserva.setText("Excluir reserva");
        BtnExcluirrreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirrreservaActionPerformed(evt);
            }
        });

        txtIDQuarto.setBackground(new java.awt.Color(255, 255, 255));
        txtIDQuarto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDQuarto.setForeground(new java.awt.Color(51, 51, 51));
        txtIDQuarto.setFocusable(false);
        txtIDQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDQuartoActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Checkout");

        txtIDCliente.setEditable(false);
        txtIDCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtIDCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtIDCliente.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nº reserva");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome cliente");

        BtnCarregarCampos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCarregarCampos.setText("Carregar Campos");
        BtnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarCamposActionPerformed(evt);
            }
        });

        txtIDreserva1.setEditable(false);
        txtIDreserva1.setBackground(new java.awt.Color(255, 255, 255));
        txtIDreserva1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDreserva1.setForeground(new java.awt.Color(51, 51, 51));
        txtIDreserva1.setFocusable(false);

        BtnEditarReserva1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEditarReserva1.setText("Editar reserva");
        BtnEditarReserva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarReserva1ActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        jDesktopPane2.setEnabled(false);
        jDesktopPane2.setFocusable(false);

        tabelaCheckout1.setBackground(new java.awt.Color(255, 255, 255));
        tabelaCheckout1.setForeground(new java.awt.Color(0, 0, 0));
        tabelaCheckout1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Reserva", "ID Cliente", "Nome", "ID Quarto", "Data Check-in",  "Data Check-in","Status"
            }
        ));
        jScrollPane2.setViewportView(tabelaCheckout1);

        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        txtNomeCliente1.setEditable(false);
        txtNomeCliente1.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCliente1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeCliente1.setForeground(new java.awt.Color(51, 51, 51));
        txtNomeCliente1.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nº Quarto");

        BtnExcluirrreserva1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnExcluirrreserva1.setText("Excluir reserva");
        BtnExcluirrreserva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirrreserva1ActionPerformed(evt);
            }
        });

        txtIDQuarto1.setBackground(new java.awt.Color(255, 255, 255));
        txtIDQuarto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDQuarto1.setForeground(new java.awt.Color(51, 51, 51));
        txtIDQuarto1.setFocusable(false);
        txtIDQuarto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDQuarto1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Data Checkin");

        txtIDCliente1.setEditable(false);
        txtIDCliente1.setBackground(new java.awt.Color(255, 255, 255));
        txtIDCliente1.setForeground(new java.awt.Color(0, 0, 0));
        txtIDCliente1.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nº reserva");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome cliente");

        txtDataCheckout1.setBackground(new java.awt.Color(255, 255, 255));
        txtDataCheckout1.setForeground(new java.awt.Color(0, 0, 0));

        BtnCarregarCampos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCarregarCampos1.setText("Carregar Campos");
        BtnCarregarCampos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarCampos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExcluirrreserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEditarReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCarregarCampos1)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane2)
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDreserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDQuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20)
                        .addComponent(txtDataCheckout1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtIDreserva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtIDQuarto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtIDCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataCheckout1)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCarregarCampos1)
                    .addComponent(BtnEditarReserva1)
                    .addComponent(BtnExcluirrreserva1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtDataCheckout.setBackground(new java.awt.Color(255, 255, 255));
        txtDataCheckout.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataCheckout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExcluirrreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEditarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCarregarCampos)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtIDQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDataCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCarregarCampos)
                    .addComponent(BtnEditarReserva)
                    .addComponent(BtnExcluirrreserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarReservaActionPerformed
        AlterarCheckin();
        JOptionPane.showMessageDialog(null, "Data de check-out Modificada");
        LimparCampos();
        listarReservas();
    }//GEN-LAST:event_BtnEditarReservaActionPerformed

    private void BtnExcluirrreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirrreservaActionPerformed
        ExcluirCheckin();
        JOptionPane.showMessageDialog(null, "Check-out excluido");
        LimparCampos();
        listarReservas();

    }//GEN-LAST:event_BtnExcluirrreservaActionPerformed

    private void txtIDQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDQuartoActionPerformed

    private void BtnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_BtnCarregarCamposActionPerformed

    private void BtnEditarReserva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarReserva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditarReserva1ActionPerformed

    private void BtnExcluirrreserva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirrreserva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExcluirrreserva1ActionPerformed

    private void txtIDQuarto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDQuarto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDQuarto1ActionPerformed

    private void BtnCarregarCampos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarCampos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCarregarCampos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarregarCampos;
    private javax.swing.JButton BtnCarregarCampos1;
    private javax.swing.JButton BtnEditarReserva;
    private javax.swing.JButton BtnEditarReserva1;
    private javax.swing.JButton BtnExcluirrreserva;
    private javax.swing.JButton BtnExcluirrreserva1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaCheckout;
    private javax.swing.JTable tabelaCheckout1;
    private javax.swing.JFormattedTextField txtDataCheckout;
    private javax.swing.JTextField txtDataCheckout1;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtIDCliente1;
    private javax.swing.JTextField txtIDQuarto;
    private javax.swing.JTextField txtIDQuarto1;
    private javax.swing.JTextField txtIDreserva;
    private javax.swing.JTextField txtIDreserva1;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeCliente1;
    // End of variables declaration//GEN-END:variables
    private void listarReservas() {
        try {
            //Cria um objeto objCadClienteDAO da classe CadClientesDAO
            ReservaDAO objCadReserva = new ReservaDAO();

            //Obtém o modelo da tabela tabelaCliente e limpa todas as linhas existentes
            DefaultTableModel model = (DefaultTableModel) tabelaCheckout.getModel();
            model.setNumRows(0);

            //Chama o método PesquisarCliente() do objeto objCadClienteDAO para obter uma lista de clientes
            // Para selecionar reservas com status 'Reservado'
            String whereClause = "status = ?";
            String[] whereArgs = new String[]{"Finalizado"};
            ArrayList<ReservaDTO> lista = objCadReserva.PesquisarReserva(whereClause, whereArgs);

            //Para cada cliente na lista, adiciona uma nova linha à tabela com os detalhes do cliente.
            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getId_cliente(),
                    lista.get(num).getNome(),
                    lista.get(num).getIdQuarto(),
                    lista.get(num).getDataCheckin(),
                    lista.get(num).getDataCheckout(),
                    lista.get(num).getStatus()
                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarReservas" + erro);
        }
    }

    public void onCheckinDataConfirmed() {
        // Atualize os dados da tabela
        listarReservas();
    }

    private void CarregarCampos() {

        //Obtém o índice da linha selecionada na tabela tabelaCliente
        int setar = tabelaCheckout.getSelectedRow();
        if (setar == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            //Para cada campo de texto, define o texto para o valor correspondente na linha selecionada da tabela.
            txtIDreserva.setText(tabelaCheckout.getModel().getValueAt(setar, 0).toString());
            txtIDCliente.setText(tabelaCheckout.getModel().getValueAt(setar, 1).toString());
            txtNomeCliente.setText(tabelaCheckout.getModel().getValueAt(setar, 2).toString());
            txtIDQuarto.setText(tabelaCheckout.getModel().getValueAt(setar, 3).toString());
            txtDataCheckout.setText(tabelaCheckout.getModel().getValueAt(setar, 5).toString());

            BtnEditarReserva.setEnabled(true);
            BtnExcluirrreserva.setEnabled(true);
        }

    }

    private void AlterarCheckin() {
        String id_reserva, data_checkout;

        id_reserva = txtIDreserva.getText();
        data_checkout = txtDataCheckout.getText();

        String formataDataCheckout = ConverterData(data_checkout);

        if (formataDataCheckout == null) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido. Por favor, use o formato dd/MM/yyyy.");
            return;
        }

        ReservaDTO objCadReservaDTO = new ReservaDTO();

        objCadReservaDTO.setId(id_reserva);
        objCadReservaDTO.setDataCheckout(formataDataCheckout);
        objCadReservaDTO.setStatus("Finalizado");

        ReservaDAO objCadReservaDAO = new ReservaDAO();

        objCadReservaDAO.AlterarDataCheckout(objCadReservaDTO);
    }

    private String ConverterData(String dateStr) {
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = inputFormat.parse(dateStr);
            return outputFormat.format(date);
        } catch (ParseException e) {
            return null;
        }
    }

    private void LimparCampos() {
        txtIDreserva.setText("");
        txtIDQuarto.setText("");
        txtIDCliente.setText("");
        txtNomeCliente.setText("");
        txtDataCheckout.setText("");
    }

    private void ExcluirCheckin() {
        String id_reserva;

        id_reserva = txtIDreserva.getText();
        ReservaDTO objCadReservaDTO = new ReservaDTO();
        objCadReservaDTO.setId(id_reserva);

        ReservaDAO objCadReservaDAO = new ReservaDAO();
        objCadReservaDAO.ExcluirReserva(objCadReservaDTO);
    }
}
