package VIEW;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author henri
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        clientes = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        consultaCliente = new javax.swing.JMenuItem();
        reservas = new javax.swing.JMenu();
        realizaReserva = new javax.swing.JMenuItem();
        consultaReserva = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        realizaCheckin = new javax.swing.JMenuItem();
        ConsultaCheckin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        realizaCheckout = new javax.swing.JMenuItem();
        consultaCheckout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));

        clientes.setBackground(new java.awt.Color(255, 255, 255));
        clientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clientes.setForeground(new java.awt.Color(102, 102, 255));
        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/clientes.png"))); // NOI18N
        clientes.setText("Clientes");
        clientes.setBorderPainted(false);
        clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientes.setMaximumSize(new java.awt.Dimension(100, 60));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        cadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/cadcliente.png"))); // NOI18N
        cadastrarCliente.setText("Cadastrar cliente");
        cadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        clientes.add(cadastrarCliente);

        consultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/pesqcliente.png"))); // NOI18N
        consultaCliente.setText("Consulta cliente");
        consultaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });
        clientes.add(consultaCliente);

        jMenuBar1.add(clientes);

        reservas.setBackground(new java.awt.Color(102, 102, 255));
        reservas.setForeground(new java.awt.Color(102, 102, 255));
        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/reserva.png"))); // NOI18N
        reservas.setText("Reservas");
        reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservas.setMaximumSize(new java.awt.Dimension(100, 60));

        realizaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/novareserva.png"))); // NOI18N
        realizaReserva.setText("Realizar Reserva");
        realizaReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaReservaActionPerformed(evt);
            }
        });
        reservas.add(realizaReserva);

        consultaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/pesqreserva.png"))); // NOI18N
        consultaReserva.setText("Consulta Reserva");
        consultaReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaReservaActionPerformed(evt);
            }
        });
        reservas.add(consultaReserva);

        jMenuBar1.add(reservas);

        jMenu3.setForeground(new java.awt.Color(102, 102, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/checkin.png"))); // NOI18N
        jMenu3.setText("Check-in");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(100, 60));

        realizaCheckin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/novocheck-in.png"))); // NOI18N
        realizaCheckin.setText("Realizar Check-in");
        realizaCheckin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizaCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaCheckinActionPerformed(evt);
            }
        });
        jMenu3.add(realizaCheckin);

        ConsultaCheckin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/verificacheckin.png"))); // NOI18N
        ConsultaCheckin.setText("Consultar Check-in");
        ConsultaCheckin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultaCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCheckinActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultaCheckin);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(102, 102, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/checkout.png"))); // NOI18N
        jMenu4.setText("Check-out");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(100, 60));

        realizaCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/novocheckout.png"))); // NOI18N
        realizaCheckout.setText("Realizar Check-out");
        realizaCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizaCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaCheckoutActionPerformed(evt);
            }
        });
        jMenu4.add(realizaCheckout);

        consultaCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/folder/verificacheckin.png"))); // NOI18N
        consultaCheckout.setText("Consultar Check-out");
        consultaCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCheckoutActionPerformed(evt);
            }
        });
        jMenu4.add(consultaCheckout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        FrmiNovoCliente objNovoCliente = new FrmiNovoCliente();
        jDesktopPane1.add(objNovoCliente);
        objNovoCliente.setVisible(true);
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        FrmRelatorioClientes objConsCliente = new FrmRelatorioClientes();
        jDesktopPane1.add(objConsCliente);
        objConsCliente.setVisible(true);
    }//GEN-LAST:event_consultaClienteActionPerformed

    private void realizaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaReservaActionPerformed
        FrmNovaReserva objNovaReserva = new FrmNovaReserva();
        jDesktopPane1.add(objNovaReserva);
        objNovaReserva.setVisible(true);
    }//GEN-LAST:event_realizaReservaActionPerformed

    private void consultaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaReservaActionPerformed
        FrmConsultaReserva objConsultaReserva = new FrmConsultaReserva();
        jDesktopPane1.add(objConsultaReserva);
        objConsultaReserva.setVisible(true);
    }//GEN-LAST:event_consultaReservaActionPerformed

    private void realizaCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaCheckinActionPerformed
        FrmCheckin objCheckin = new FrmCheckin();
        jDesktopPane1.add(objCheckin);
        objCheckin.setVisible(true);
    }//GEN-LAST:event_realizaCheckinActionPerformed

    private void ConsultaCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCheckinActionPerformed
        FrmConsultaCheckin objConsultaCheckin = new FrmConsultaCheckin();
        jDesktopPane1.add(objConsultaCheckin);
        objConsultaCheckin.setVisible(true);
    }//GEN-LAST:event_ConsultaCheckinActionPerformed

    private void realizaCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaCheckoutActionPerformed
        FrmCheckout objCheckout = new FrmCheckout();
        jDesktopPane1.add(objCheckout);
        objCheckout.setVisible(true);
    }//GEN-LAST:event_realizaCheckoutActionPerformed

    private void consultaCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCheckoutActionPerformed
        FrmConsultaCheckout objConsultaCheckout = new FrmConsultaCheckout();
        jDesktopPane1.add(objConsultaCheckout);
        objConsultaCheckout.setVisible(true);
    }//GEN-LAST:event_consultaCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaCheckin;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenu clientes;
    private javax.swing.JMenuItem consultaCheckout;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaReserva;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem realizaCheckin;
    private javax.swing.JMenuItem realizaCheckout;
    private javax.swing.JMenuItem realizaReserva;
    private javax.swing.JMenu reservas;
    // End of variables declaration//GEN-END:variables
}
